# $ docker images
# REPOSITORY      TAG       IMAGE ID       CREATED          SIZE
# krirag-ui       latest    c33e98935624   18 minutes ago   13.3GB
# krirag-api      latest    d8b483d585ea   2 days ago       4.41GB
version: "0.1"

services:
  server:
    container_name: krirag-api
    image: krirag-api:latest
    build:
      context: .
      dockerfile: llama.cpp/.devops/llama-server-cuda.Dockerfile 
    volumes:
      - ~/LLM_STORE:/models
    ports:
      - "8502:8502"
    networks:
      - krirag-net
    environment:
      - MODEL_PATH=/models/gemma-2-9b-it-Q5_K_M.gguf
      - N_CONTEXT_LEN=4096
      - NGPU=100

  frontend:
    container_name: krirag-ui
    image: krirag-ui:latest
    build:
      context: .
      dockerfile: krirag.dockerfile
    ports:
      - "8501:8501"
    networks:
      - krirag-net
    depends_on:
      - server

networks:
  krirag-net:
    driver: bridge