FROM python:3.10-slim
WORKDIR /app

COPY src/ /app
RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential
RUN python3 -m pip install --no-cache-dir -r requirements.txt
RUN python3 install.py
EXPOSE 8501
CMD ["bash", "-c", "streamlit run ui.py"]
